### ISSUE TITLE
Can't send tells to a person with a space in their name

### ISSUE THREAD

**Issue by AyrtonStout** [lazymeadow/best-ever-chat#10]
If my name is "A Tron" and I try to send a tell to myself it says "A is not connected to chat."

**Comment by lazymeadow** [comment]
need to parse more tokens if it might match a username with spaces.
probably: 'A Name' and 'A Name Two' will just depend on what you type. '/t A Name fjdslfjdsl' would go to 'A Name', but '/t A Name Two fdjlsfjldsjl' would need to go to 'A Name Two'.
make sure it keeps case sensitivity.
