### ISSUE TITLE
Icons in the left panel get cut off

### ISSUE THREAD

**Issue by mrnyby** [lazymeadow/best-ever-chat#107]
Most of the icons in the left panel are getting cut off. Zooming doesn't seem to help, so maybe it's font size related or something.

<img width="1019" alt="screen shot 2018-11-19 at 9 47 08 am" src="https://user-images.githubusercontent.com/9452628/48718007-26259900-ebe0-11e8-808b-8da18c86fec4.png">

**Comment by lazymeadow** [comment]
so on a mac when you are using the trackpad instead of a mouse, the scrollbars don't have width and auto-hide. this is causing everything to be off because `overflow-y: scroll` means nothing to mac

**Comment by lazymeadow** [comment]
you can make the scrollbars on mac os always appear if you really don't want this to happen, otherwise i'm not going to code around the fact that you're using a dumb computer
