### ISSUE TITLE
Watch your profamity

### ISSUE THREAD

**Issue by aaronrussell94** [lazymeadow/best-ever-chat#18]
[I am deeply offended by some of the language coming from some of the more crude users of this chat. I've been forced to read the S word, B, word, and even the F word. It would be funny if this foul language was automatically replaced by more family friendly verbage.](https://www.youtube.com/watch?v=hpigjnKl7nI)

For example:
- Shit -> poop, snot
- Damn -> dagnabit, dang, darn
- Bitch -> witch, bee
- God -> gosh, golly
- Fuck -> frig, fudge, flip, fart
- Ass -> bum, butt, backside

**Comment by lazymeadow** [comment]
fork
shirt, shoot

**Comment by lazymeadow** [comment]
Also, maybe throw some emoji susbtitutions in there
