### ISSUE TITLE
maybe there should be an option for images to be collapsed by default

### ISSUE THREAD

**Issue by lazymeadow** [lazymeadow/best-ever-chat#41]
sometimes we are at work and we don't want people to send inappropriate gifs that we then have to hide from our coworkers or delete manually from the dom. that would be nice.

**Comment by AyrtonDetex** [comment]
By request of @aaronrussell94 

![toast-butter](https://user-images.githubusercontent.com/19576769/31196495-3b650152-a90b-11e7-800c-dea94ad535e8.gif)

**Comment by lazymeadow** [comment]
also maybe have a checkbox so the image can be explicitly flagged as nsfw and you don't open it at all.
