### ISSUE TITLE
The typing icon appears when I am typing in general room

### ISSUE THREAD

**Issue by lanhchop** [lazymeadow/best-ever-chat#55]
The typing indicator appears no matter what room I'm in. If I'm typing in a private chat room, I don't want the general audience to wait for me to finish typing when I'm not chatting in there.

**Comment by lazymeadow** [comment]
the typing indicator should follow the room you are in. if you are in general, and switch to a private room, it should remove your typing indicator from general and only display it in the private room. most weirdness should have been fixed with #54 ... but if not, let me know.
